name: Git Actions Test

on:
  pull_request:
    types:
      - opened
    branches:
      - 'master'

env:
  branch: 'master' # same as above

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Test time"
        run: echo $branch
