name: Git Actions Test

on: workflow_dispatch

env:
  branch: 'master' # same as above

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Test time"
        run: echo $branch
